# Generated by: free fleet (llm_router)
import sys, os, sqlite3
sys.path.insert(0, r'C:\Users\Sean\Documents\GitHub\Willow\core')
from build_rag_simple import index_repo

GITHUB = r'C:\Users\Sean\Documents\GitHub'
DB_PATH = r'C:\Users\Sean\Documents\GitHub\Willow\core\rag.db'

repos = [
    'agents',
    'Aionic-Claude-Skills', 
    'SAFE',
    'safe-app-dating-wellbeing',
    'safe-app-utety-chat',
    'vision-board',
    'die-namic-system',
]

for repo in repos:
    path = os.path.join(GITHUB, repo)
    if os.path.exists(path):
        print(f"Indexing {repo}...", flush=True)
        count = index_repo(path, repo)
        print(f"  {repo}: {count} chunks", flush=True)
    else:
        print(f"  SKIP {repo} (not found)", flush=True)

# Final totals
conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()
cur.execute('SELECT repo, COUNT(*) FROM chunks GROUP BY repo ORDER BY COUNT(*) DESC')
print("\nFINAL RAG TOTALS:")
total = 0
for repo, count in cur.fetchall():
    print(f"  {repo}: {count}")
    total += count
print(f"  TOTAL: {total}")
conn.close()
